### ISSUE TITLE
crash after download

### ISSUE THREAD

**Issue by CodingPro1234** [MinicraftPlus/minicraft-plus-revived#482]
when i downloaded the jar file for the minicraft+ there was an error
i dont know if there is something wrong with java or the game but it never works.
i redownloaded 3 times and its still not working. video:    

https://github.com/MinicraftPlus/minicraft-plus-revived/assets/113947915/093917a6-fcee-4c7d-a399-6b9171a6d2f1

as you can see i have lots of the same minicraft+ downloads because i was
trying to get it to work. please help

**Comment by Litorom** [comment]
This bug is fixed by deleting your preferences file. Which saves your settings.

From Tutorials on our discord by Chris J.:
the Preferences file for minicraft plus is stored in `%appdata%\playminicraft\mods\Minicraft_Plus\`

deleting this can fix your game not starting up sometimes (specifically if the error trace has `loadPrefs` in it somewhere)

**Comment by CodingPro1234** [comment]
ok thanks

**Comment by CodingPro1234** [comment]
it worked
